[package]
name = "governance_canister"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]
path = "lib.rs"

[dependencies]
candid = "0.10.13"
ic-cdk = "0.17.2"
ic-cdk-macros = "0.17.2"
serde = { version = "1.0", features = ["derive"] }